# Generated by Django 3.2.9 on 2021-11-26 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
