# Generated by Django 3.2.9 on 2021-11-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_like_tweets'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag_tweets',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hashtag_tweets',
            name='hashtag',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Hashtags',
        ),
    ]
